# The docker compose system for the michael fields MEAN stack application

version: '3'

services:
  angular:
    build: ./mf-angular
    ports:
      - "4200"
    environment:
      VIRTUAL_HOST: mf.dev-cdh.org

  database:
    image: mongo
    ports:
      - 27017:27017

  express:
    build: ./mf-api
    ports:
      - 3000:3000
    links:
      - database


networks:
  default:
    external:
      name: nginx-proxy
