#!/bin/bash

# Title: imagedownload
# Author: Caleb Kitzmann
# Description: This bash script makes a directory called notebook_<num> and
#              changes into that directory. It then loops through each url
#              within a certain range of manuscript numbers and then does a wget
#              command on the url which downloads the images to the new
#              directory.

echo Specify notebook and manuscript number seperated by a space
read notebook_num manu_num

mkdir ../mf-angular/src/assets/images/notebook_$notebook_num && cd ../mf-angular/src/assets/images/notebook_$notebook_num

for url in 'http://tundra.csd.sc.edu/vllc/img/field_scans/add_ms_'${manu_num}'/JPEG/Add_ms_'${manu_num}'_'{001..700}'.jpg'
do
  if wget "$url"
  then
    failed=
  elif [ "$failed" ]
  then
    break
  else
    failed=yes
  fi
done
