#!/bin/bash

echo Specify notebook and manuscript number seperated by a space
read notebook_num manu_num

mkdir notebook_$notebook_num && cd notebook_$notebook_num

for url in 'http://tundra.csd.sc.edu/vllc/img/field_scans/add_ms_'${manu_num}'/JPEG/add_ms_'${manu_num}'-'{001..700}'.jpg'
do
  if wget "$url"
  then
    failed=
  elif [ "$failed" ]
  then
    break
  else
    failed=yes
  fi
done
